using FluentNHibernate.Mapping;

namespace SnackMachine.Logic.NHIbernate.Mapping
{
    public class SnackMachineMap: ClassMap<Model.SnackMachine>
    {
        public SnackMachineMap()
        {
            Id(x => x.Id)
                .Column("SnackMachine_ID") // If column name different from Id
                                           //.GeneratedBy.Assigned(); - Specify only If identify column value is generated by some strategy (guid or hilo etc.)
                ;
            Component(x => x.MoneyInside, y =>
            {
                y.Map(x => x.FiveCentCount);
                y.Map(x => x.TenCentCount);
                y.Map(x => x.OneDollarCount);
                y.Map(x => x.FiveDollarCount);

            });

            Map(x => x.Name);

        }
    }
}
